# @Author: Simon Dahan
# @Last Modified time: 2022-01-12 14:11:23
resolution:
  ico: 6            ## full mesh resolution
  sub_ico: 4        ## patching grid resolution

data:
  data_path: ../../data/ico_res_{}/{}/{}
  task: scan_age #scan_age # birth_age
  configuration: template #template # native
  dataset: dHCP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

logging:
  folder_to_save_model: "../../logs/SiT/"

training:
  LR: 0.00001
  bs: 16
  bs_val: 1
  epochs: 30
  gpu: 1  
  l1loss: False
  testing: True
  val_epoch: 10
  load_weights_ssl: False
  load_weights_imagenet: False
  save_ckpt: True
  finetuning: True
  dataset_ssl: 'dhcp'
  use_confounds: False

weights: 
  ssl_mpp: '..' # path to .pt checkpoint
  imagenet: 'vit_tiny_patch16_224' #ViT(dim=192, depth=12, heads=3,mlp_dim=768,dim_head=64)
  #imagenet: 'vit_small_patch16_224' #ViT(dim=384, depth=12, heads=6,mlp_dim=1536,dim_head=64)
  #imagenet: 'vit_base_patch16_224' #ViT(dim=768, depth=12, heads=12,mlp_dim=3072,dim_head=64)
            
transformer:
  dim: 96 #96, 48
  depth: [2,2,6,2] # [1,1,3,1] [2,2,6,2] number of blocks per layer
  heads: [3,6,12,24] # number of head per layer
  channels:  [0,1,2,3] #[0,1] for working memory and [0,1,2,3] for cortical metrics, rsns [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40], [UKB;rsns] [3,5,8,9,10] 
  window_size: [64,64,64,80] #320,80, [64,64,64,320], [320,320,320,80]
  window_size_factor: 4
  mlp_ratio: 4
  num_classes: 1
  dropout: 0.0
  attention_dropout: 0.0
  drop_path_rate: 0.1 #0.1 default to try
  use_pos_emb: False
  shifted_attention: True
  model: ms-sit #ms-sit

optimisation:
  optimiser: SGD

Adam:
  weight_decay: 0.

AdamW:
  weight_decay: 0.
SGD:
  weight_decay: 0.
  momentum: 0.9
  nesterov: False
  
StepLR: 
  stepsize: 1000
  decay: 0.5

CosineDecay:
  T_max: 5000
  eta_min: 0.0001

sub_ico_0:
    num_patches: 20 
    num_vertices: 2145 

sub_ico_1:
    num_patches: 80 
    num_vertices: 561 

sub_ico_2:
    num_patches: 320
    num_vertices: 153 

sub_ico_3:
    num_patches: 1280
    num_vertices: 45

sub_ico_4:
    num_patches: 5120
    num_vertices: 15

sub_ico_5:
    num_patches: 20480
    num_vertices: 6
